# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-clojure:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout repository
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # tag: v4.22

      - name: Setup java 21 as default java
        run: |
          echo "JAVA_HOME=$JAVA_HOME_21_X64" >> $GITHUB_ENV
          echo "$JAVA_HOME_21_X64/bin" >> $GITHUB_PATH
        shell: bash

      - name: Install clojure + tools
        uses: DeLaGuardo/setup-clojure@3fe9b3ae632c6758d0b7757b0838606ef4287b08 # tag 13.2
        with:
          cli: latest
          bb: latest
          cljfmt: latest
          clj-kondo: latest

      - name: Cache clojure dependencies
        uses: actions/cache@638ed79f9dc94c1de1baef91bcab5edaa19451f4 # tag: v4.2.3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: cljdeps-${{ hashFiles('**/deps.edn') }}
          restore-keys: cljdeps-

      - name: Run test suite + linters
        run: bb ci
